apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ckgc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0067-tenant/tkrw-pr712-0075-0067-app/devfile-sample-ckgc@sha256:976afb4e7b53f3ec4dc4ddbe292330a8498522c0fc7a45a68e9a0d979541a93b
        name: my-nodejs
        resources: {}
status: {}
